import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './theme-config.css';
import "./globals.css";
import NavBar from './NavBar';
import "@radix-ui/themes/styles.css";

import { Container, Theme } from '@radix-ui/themes';
import AuthProvider from './auth/Provider';



const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});


export const metadata: Metadata = {
  title: "Issue Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={inter.variable} lang="en">
      <body
        className={inter.variable}
      >
        <AuthProvider>
          <Theme accentColor="sky" radius="small">
            <NavBar />
            <Container>
              <main className='p-5'>
                {children}
              </main>
            </Container>

            {/* <ThemePanel></ThemePanel> */}
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
