import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './theme-config.css';
import "./globals.css";
import NavBar from './NavBar';
import "@radix-ui/themes/styles.css";

import { Theme } from '@radix-ui/themes';



const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});


export const metadata: Metadata = {
  title: "Issue Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={inter.variable} lang="en">
      <body
        className={inter.variable}
      >
        <Theme accentColor="sky" radius="small">
          <NavBar />
          <main className='p-5'>
            {children}
          </main>
          {/* <ThemePanel></ThemePanel> */}
        </Theme>
      </body>
    </html>
  );
}
